# Build customization
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - main: ./cmd/hasselhoffme/
    env:
      - CGO_ENABLED=0
    binary: hasselhoffme
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
archives:
  - format: binary
