# Build customization
builds:
  - main: .
    env:
      - CGO_ENABLED=0
    binary: hasselhoffme
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archive:
  format: binary
