language: go
os:
- linux
go:
- 1.x
env:
- GO111MODULE=on
before_install:
- go mod download

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
