language: go
os:
- linux
go:
- 1.10
before_install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASES_API_KEY
  file: hasselhoffme
  on:
    repo: ervitis/hasselhoffme
