language: go
os:
- linux
go:
- 1.x
before_install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL http://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
